env: local
token_ttl: 1h
ticket_ttl: 5s
secret: somesecret
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
cors:
  allowed_origins:
    - http://127.0.0.1:5173
  debug: true
database:
  host: localhost:5432
  name: chatsy
  username: postgres
  password: postgres
